services:
  - type: web
    name: selleaise-backend
    env: docker
    plan: free
    repo: https://github.com/aadhamu/selleaise
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: [YOUR TRUEHOST IP OR DOMAIN]
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: ewkkgloj_sellease
      - key: DB_USERNAME
        value: ewkkgloj_selleuser
      - key: DB_PASSWORD
        value: zallaH2025!
