services:
  - type: web
    name: sellease
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "php artisan migrate --force && apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Hqjbc2q91dzBaQx5t/22ssrzwDSkKNiLchSUDiG3SC8=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://sellease.onrender.com

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1hi6a0dl3ps738mtigg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: sellease_user
      - key: DB_USERNAME
        value: sellease
      - key: DB_PASSWORD
        value: hcwQhHDMLZowzJgqMYgeTHv6utdUNvdP

      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
