services:
  - type: web
    name: selleaise
    env: php
    plan: free
    region: oregon
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64EBAl1CH42Ag6DqP58WYfMBrjbJRalxKgW/f4Z5sXpfA=
      - key: APP_URL
        value: https://selleaise.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host-from-truehost
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
