services:
  - type: web
    name: sellease
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:ZJt9Ej4C/72Y+F8cPCtT5O6/z6C3YvHfEk05Q2x0/z8=
      - key: APP_URL
        value: https://sellease.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1hi6a0dl3ps738mtigg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: sellease_user
      - key: DB_USERNAME
        value: sellease
      - key: DB_PASSWORD
        value: hcwQhHDMLZowzJgqMYgeTHv6utdUNvdP
      - key: PAYSTACK_PUBLIC_KEY
        value: pk_test_6299f4ba1dc71a65cdb9bdfa4eb7c2c67bfcd939
      - key: PAYSTACK_SECRET_KEY
        value: sk_test_0bd2149ffbc054b590a246dd299dca0f4b1c68fd
